version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - /workspace/blog-data/mysql/data:/var/lib/mysql
      - /workspace/blog-data/mysql/conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci